Sprint 1 - User Sevice Created
Akash-Ping-NT/ROP_BackEnd pull request #1
Opened 2024-08-23 07:27 UTC by Akash-Ping-NT

2024-08-23 11:00 UTC, alok-nucleusteq requested changes
Resolve the reviews asap

2024-08-23 11:00 UTC, alok-nucleusteq commented on Restaurant_Service/src/main/java/com/microservice/RestaurantService/Service/ServiceImpl/RestaurantServiceImpl.java
> +    public RestaurantServiceImpl(RestaurantRepository restaurantRepository, UserServiceClient userServiceClient) {
write complete impl - implementation

2024-08-23 11:00 UTC, alok-nucleusteq commented on Restaurant_Service/src/main/java/com/microservice/RestaurantService/Service/ServiceImpl/RestaurantServiceImpl.java
> +            throw new IllegalArgumentException("User is not authorized to create a restaurant.");
IllegalArgumentException use custom exception that is related to the error like unauthorized exception

2024-08-23 11:00 UTC, alok-nucleusteq commented on Restaurant_Service/src/main/java/com/microservice/RestaurantService/Service/ServiceImpl/RestaurantServiceImpl.java
> +        restaurant.setOwnerId(userDtoResponse.getId());
Remove unnecessary comments

2024-08-23 11:00 UTC, alok-nucleusteq commented on Restaurant_Service/src/main/java/com/microservice/RestaurantService/controller/RestaurantController.java
> +@RestController
add java docs

2024-08-23 11:00 UTC, alok-nucleusteq commented on Restaurant_Service/src/main/java/com/microservice/RestaurantService/dtos/request/CreateRestaurantRequest.java
> +    private LocalDateTime registrationDate;
Remove unnecessary comments

2024-08-23 11:00 UTC, alok-nucleusteq commented on Restaurant_Service/src/main/java/com/microservice/RestaurantService/dtos/request/CreateRestaurantRequest.java
> +
Implement hashcode and equal method in every entity and dtos

2024-08-23 11:00 UTC, alok-nucleusteq commented on Restaurant_Service/src/main/java/com/microservice/RestaurantService/dtos/request/CreateRestaurantRequest.java
> +    }
Implement toString method in dtos only

2024-08-23 11:00 UTC, alok-nucleusteq commented on Restaurant_Service/src/main/java/com/microservice/RestaurantService/dtos/response/CreateRestaurantResponse.java
> +    public String getOwnerName() {
In entity implement hascode and equal method only not toString

2024-08-23 11:00 UTC, alok-nucleusteq commented on Restaurant_Service/src/main/java/com/microservice/RestaurantService/entity/Restaurant.java
> +    @Column(nullable = false, unique = true)
validate email with regular expression (format should be only akash.ping@nucleusteq.com)

2024-08-23 11:00 UTC, alok-nucleusteq commented on Restaurant_Service/src/main/java/com/microservice/RestaurantService/entity/Restaurant.java
> +
name should be only in string numbers not allowed

2024-08-23 11:00 UTC, alok-nucleusteq commented on Restaurant_Service/src/main/java/com/microservice/RestaurantService/entity/Restaurant.java
> +    @Column(name = "contact_no", nullable = false)
Only number should be allowed and should not be more than 10 digits

2024-08-23 11:00 UTC, alok-nucleusteq commented on Restaurant_Service/src/main/java/com/microservice/RestaurantService/entity/Restaurant.java
> +
toString method should be in dtos only

2024-08-23 11:00 UTC, alok-nucleusteq commented on Restaurant_Service/src/main/java/com/microservice/RestaurantService/package-info.java
> +/**
remove this file from here add checkstyle rule to ignore this error

2024-08-23 11:00 UTC, alok-nucleusteq commented on Restaurant_Service/src/test/java/com/microservice/RestaurantService/RestaurantServiceApplicationTests.java
> +@SpringBootTest
implement properly (for service use mockito)

2024-08-23 11:00 UTC, alok-nucleusteq commented on userService/src/main/java/com/microservice/userService/controller/UserController.java
> +            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Login Failed Check Credential", e);
implement logger in the end of the method also before ending the execution

2024-08-23 11:00 UTC, alok-nucleusteq commented on userService/src/main/java/com/microservice/userService/controller/UserController.java
> +    public ResponseEntity<UserAddressResponseDTO> addAddress(
logger should be implemented in every method of controller and service 
(in the start and end of the method)

2024-08-23 11:00 UTC, alok-nucleusteq commented on userService/src/main/java/com/microservice/userService/controller/UserController.java
> +            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Failed to add address", e);
Use proper exception related to issues

2024-08-23 11:00 UTC, alok-nucleusteq commented on userService/src/main/java/com/microservice/userService/controller/UserController.java
> +        } catch (UserNotFoundException e) {
Here should be only one exception multiple exception you can throw in service

2024-08-23 11:00 UTC, alok-nucleusteq commented on userService/src/main/java/com/microservice/userService/controller/package-info.java
> +/**
remove package info files

2024-08-23 11:00 UTC, alok-nucleusteq commented on userService/src/main/java/com/microservice/userService/dtos/request/UserAddressRequestDTO.java
> +    private Long id;
Add java docs and validation

2024-08-23 11:00 UTC, alok-nucleusteq commented on userService/src/main/java/com/microservice/userService/dtos/request/UserLoginRequestDTO.java
> +    @NotBlank(message = "Email is mandatory")
validate email

2024-08-23 11:00 UTC, alok-nucleusteq commented on userService/src/main/java/com/microservice/userService/dtos/request/UserRegistrationRequestDTO.java
> +    @Email(message = "Email should be valid")
where are you checking image is valid ? ("Email should be valid")

2024-08-23 11:00 UTC, alok-nucleusteq commented on userService/src/main/java/com/microservice/userService/dtos/response/CommonResponseDTO.java
> +package com.microservice.userService.dtos.response;
Add java docs

2024-08-23 11:00 UTC, alok-nucleusteq commented on userService/src/main/java/com/microservice/userService/dtos/response/UserRegistrationResponseDTO.java
> +    private String message; // A message to indicate successful registration
remove comments add in javadoc

2024-08-23 11:00 UTC, alok-nucleusteq commented on userService/src/main/java/com/microservice/userService/entity/User.java
> +    @Column(nullable = false, length = 255)
follow above reviews

2024-08-27 07:42 UTC, Akash-Ping-NT commented on Restaurant_Service/src/main/java/com/microservice/RestaurantService/Service/ServiceImpl/RestaurantServiceImpl.java
> +    public RestaurantServiceImpl(RestaurantRepository restaurantRepository, UserServiceClient userServiceClient) {
Yes Alok , I have made the changes.

2024-08-27 07:43 UTC, Akash-Ping-NT commented on Restaurant_Service/src/main/java/com/microservice/RestaurantService/Service/ServiceImpl/RestaurantServiceImpl.java
> +            throw new IllegalArgumentException("User is not authorized to create a restaurant.");
Done with implementing custom exception.

2024-08-27 07:43 UTC, Akash-Ping-NT commented on Restaurant_Service/src/main/java/com/microservice/RestaurantService/Service/ServiceImpl/RestaurantServiceImpl.java
> +        restaurant.setOwnerId(userDtoResponse.getId());
Implemented

2024-08-27 07:43 UTC, Akash-Ping-NT commented on Restaurant_Service/src/main/java/com/microservice/RestaurantService/controller/RestaurantController.java
> +@RestController
Done with adding java docs.

2024-08-30 05:49 UTC, merged